_BASE_: "mask_rcnn_R_50_FPN.yaml"
MODEL:
  META_ARCHITECTURE: "FeatSaver"
  SAVE_SEQ_FEATS: True
  WEIGHTS: "detectron2://Cityscapes/mask_rcnn_R_50_FPN/142423278/model_final_af9cf5.pkl"
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.5
INPUT:
  MIN_SIZE_TRAIN: (1024,)
  SEQ_LEN: 6
  #SEQ_INTERVAL: 3
  SEQ_INTERVAL: 1
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 1.0e-4
  STEPS: (18000,)
  MAX_ITER: 24000
  IMS_PER_BATCH: 8
  #IMS_PER_BATCH: 1
TEST:
  EVAL_PERIOD: 10000000000